# Generated by Django 5.2.8 on 2025-11-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_delete_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
